name: Buildpack Registry Namespace Notifier
on:
  push:
    branches:
      - main

jobs:
#  email-maintainers:
#    name: Email Maintainers
#    runs-on: ubuntu-latest
#    steps:
#    - name: Send mail
#      uses: dawidd6/action-send-mail@v2
#      with:
#        server_address: smtp.gmail.com
#        server_port: 465
#        username: "${{ secrets.MAIL_USERNAME }}"
#        password: "${{ secrets.MAIL_PASSWORD }}"
#        subject: "[${{ github.repository }}] Registry Namespace updated"
#        body: Maintainers, there are some changes in ${{ github.repository }} repository.
#        to: ${{ secrets.CNB_MAINTAINERS_EMAIL }}
#        from: ${{ secrets.MAIL_SENDER }}


  slack-notifier:
    name: Slack Channel Notify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Channel Notify
      uses: rtCamp/action-slack-notify@v2.2.1
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: ${{ github.repository }}
        # Only include the commit SHA/message in the notification, and not the event type or ref
        # (which are always 'push' and 'refs/heads/main'), or the GitHub Actions workflow URL.
        MSG_MINIMAL: "commit"
